### ISSUE TITLE
Create new spreadsheet if ID omitted

### ISSUE THREAD

**Issue by timwis** [kren1/tosheets#1]
Great utility! I'm gonna use this all the time. I expect most times I use it, though, I'll want to pipe data into a new spreadsheet. Could this tool create a new spreadsheet if the ID is omitted?

**Comment by AFNobody** [comment]
Submitted a pull request to provide that functionality + updating sheets (instead of just append)
`
echo '1 2\n3 4' | ./tosheets.py -c A1 --new-sheet=testing                                                                                             
00SJh7yNMmbcSd_8dNrpwGiX5cb2cGIKhkhSeUCruCdM
`

That probably meets your needs, yeah?

**Comment by kren1** [comment]
Cool idea @timwis  and thanks @AFNobody for the PR. I'll try to get this merged and released shortly.

**Comment by kren1** [comment]
This should now be release in version 0.2.0, all thanks to @AFNobody .

**Comment by timwis** [comment]
Woohoo! Thanks @AFNobody and @kren1 !
